/**
 * Workspace persistence (M5): the v5 document round-trips through JSON and
 * `applyWorkspaceDoc`, the v4 importer maps a REAL legacy blob (captured
 * from the v1 template code — tests/e2e/fixtures/workspace-v4.json)
 * without losing anything the user can see, and a v1-era blob walks the
 * whole chain v1 → v4 → v5.
 */
import { describe, expect, it } from "vitest";
import v4Blob from "../../tests/e2e/fixtures/workspace-v4.json";
import { Store } from "./store";
import type { AppState, SweepProgram } from "./state";
import { HW_TRACE_IDS, initialState } from "./state";
import { migrate, snapshotWorkspace, WS_VERSION } from "./persist";
import { applyWorkspaceDoc } from "./actions/workspace";
import { templates } from "./templates";
import type { Ipc } from "../ipc/ipc";

const stubIpc: Ipc = {
  call: () => Promise.resolve(null as never),
};

function freshStore(): Store<AppState> {
  return new Store(initialState(), { freeze: true });
}

describe("v5 document", () => {
  it("snapshot → JSON → migrate → apply round-trips the bench", () => {
    const store = freshStore();
    // A bench with something in every slice: rename, collapse, tile tweak.
    store.update("test/seed", (s) => ({
      ...s,
      workspace: { name: "Bench A", collapsed: ["programs"] },
      layout: {
        ...s.layout,
        tiles: {
          ...s.layout.tiles,
          "tile-1": { ...s.layout.tiles["tile-1"], fdUnit: "dbu" as const },
        },
      },
    }));

    const doc = migrate(JSON.parse(JSON.stringify(snapshotWorkspace(store.get()))));
    expect(doc).not.toBeNull();

    const dest = freshStore();
    expect(applyWorkspaceDoc(dest, stubIpc, doc!)).toBe(true);
    const s = dest.get();
    expect(s.workspace).toEqual({ name: "Bench A", collapsed: ["programs"] });
    expect(s.layout.tiles["tile-1"].fdUnit).toBe("dbu");
    // The restored snapshot is identical to the saved one (stability: the
    // auto-save must not thrash on load).
    expect(snapshotWorkspace(s)).toEqual(doc);
  });

  it("normalizes transients: nothing plays or runs after a load", () => {
    const store = freshStore();
    store.update("test/play", (s) => ({
      ...s,
      sources: {
        ...s.sources,
        byId: {
          "src-sine-1": { ...s.sources.byId["src-sine-1"], playing: true },
        },
      },
    }));
    const doc = snapshotWorkspace(store.get());
    expect(doc.sources.byId["src-sine-1"].playing).toBe(false);
  });

  it("every built-in template survives JSON + migrate and references real traces", () => {
    for (const t of templates()) {
      const doc = migrate(JSON.parse(JSON.stringify(t.make())));
      expect(doc, t.name).not.toBeNull();
      for (const tileId of doc!.layout.order) {
        for (const traceId of doc!.layout.tiles[tileId].traces) {
          expect(doc!.traces.byId[traceId], `${t.name}/${tileId}/${traceId}`).toBeDefined();
        }
      }
      // Loadable onto a live store without throwing.
      expect(applyWorkspaceDoc(freshStore(), stubIpc, doc!)).toBe(true);
    }
  });
});

describe("v4 importer (real legacy blob)", () => {
  // The fixture is EXACTLY what the v1 frontend wrote for saveNamed("Amp /
  // DAC bench") — generated by src/dashboard/store.ts, not hand-written.
  const doc = migrate(JSON.parse(JSON.stringify(v4Blob)))!;

  it("accepts the blob", () => {
    expect(doc).not.toBeNull();
    expect(doc.version).toBe(WS_VERSION);
    expect(doc.name).toBe("Amp / DAC bench");
  });

  it("maps the generator to a sine source with its params and route", () => {
    expect(doc.sources.order).toContain("t-gen");
    const gen = doc.sources.byId["t-gen"];
    expect(gen).toMatchObject({
      kind: "sine",
      route: "both",
      playing: false,
      frequencyHz: 1000,
      levelDbv: -12,
    });
  });

  it("maps the sweeps to programs + result traces", () => {
    expect(doc.programs.order).toEqual(["t-thd", "t-fr"]);
    const thd = doc.programs.byId["t-thd"] as SweepProgram;
    expect(thd.kind).toBe("sweep");
    expect(thd.params).toMatchObject({
      measurement: "thd",
      channel: "left",
      startHz: 20,
      endHz: 20000,
      levelDbfs: -6,
    });
    const fr = doc.programs.byId["t-fr"] as SweepProgram;
    expect(fr.params.measurement).toBe("fr");
    expect(doc.traces.byId["t-thd"]?.source.kind).toBe("program");
    expect(doc.traces.byId["t-fr"]?.source.kind).toBe("program");
    expect(doc.traces.byId["t-thd"]?.label).toBe("THD vs freq");
  });

  it("maps graphs to tiles: kind, membership, chips, pattern", () => {
    expect(doc.layout.pattern).toBe("2x2");
    expect(doc.layout.order).toEqual(["g-spec", "g-thd", "g-fr", "g-scope"]);
    expect(doc.layout.tiles["g-spec"]).toMatchObject({
      kind: "spectrum",
      traces: [HW_TRACE_IDS.inputL],
      measures: ["thd", "thddb", "thdn", "sinad"],
    });
    expect(doc.layout.tiles["g-thd"].kind).toBe("sweep");
    expect(doc.layout.tiles["g-thd"].traces).toEqual(["t-thd"]);
    expect(doc.layout.tiles["g-fr"]).toMatchObject({
      kind: "sweep",
      showPhase: true,
      traces: ["t-fr"],
    });
    expect(doc.layout.tiles["g-scope"]).toMatchObject({
      kind: "scope",
      traces: [HW_TRACE_IDS.inputL],
      measures: ["rms", "peak", "crest"],
    });
  });

  it("loads onto a live store", () => {
    const store = freshStore();
    expect(applyWorkspaceDoc(store, stubIpc, doc)).toBe(true);
    expect(store.get().programs.order).toHaveLength(2);
    // The 4 hardware endpoints are still there.
    for (const id of Object.values(HW_TRACE_IDS)) {
      expect(store.get().traces.byId[id]).toBeDefined();
    }
  });
});

describe("v1 → v5 chain", () => {
  // A v1 blob as the v1-era app wrote it (from the legacy e2e spec): the
  // generator still has the retired analyze/capture flags and no
  // extraTones; the script has no role yet.
  const v1 = {
    version: 1,
    name: "Legacy v1",
    layout: { pattern: "1", slots: ["g1"] },
    graphs: [
      {
        id: "g1",
        title: "Spectrum",
        domain: "fd",
        series: [{ traceId: "hw-in-left", domain: "fd" }],
        x: { log: true },
        y: { autoscale: true },
      },
    ],
    traces: [
      { id: "hw-in-left", source: { kind: "hw_input", channel: "left" }, label: "Input L" },
      {
        id: "gen-legacy",
        label: "Old Sine",
        source: {
          kind: "generator",
          params: {
            waveform: "sine",
            frequency: 1000,
            level: -12,
            output: "both",
            window: 8192,
            analyze: "left",
            capture: false,
          },
        },
      },
      {
        id: "script-legacy",
        label: "Old Meas",
        source: {
          kind: "script",
          params: { name: "Old Meas", source: "let c = acquire();\nprint(c.rms);" },
        },
      },
    ],
  };

  it("migrates without losing traces and classifies the script", () => {
    const doc = migrate(JSON.parse(JSON.stringify(v1)));
    expect(doc).not.toBeNull();
    // The generator became a sine source (tone list empty), retired flags
    // gone by construction of the v2 shape.
    expect(doc!.sources.byId["gen-legacy"]).toMatchObject({
      kind: "sine",
      route: "both",
      levelDbv: -12,
      extraTones: [],
    });
    // The acquire() script is a measurement PROGRAM (v1→v2 classification).
    expect(doc!.programs.byId["script-legacy"]).toMatchObject({
      kind: "script",
      role: "measurement",
    });
    expect(doc!.traces.byId["script-legacy"]?.label).toBe("Old Meas");
    // The graph landed as a spectrum tile on Input L.
    expect(doc!.layout.tiles["g1"]).toMatchObject({
      kind: "spectrum",
      traces: ["hw-in-left"],
    });
  });

  it("rejects garbage", () => {
    expect(migrate(null)).toBeNull();
    expect(migrate({ version: 99 })).toBeNull();
    expect(migrate({ version: 4 })).toBeNull(); // no layout/graphs/traces
  });
});
