/**
 * INVARIANT FAMILY F — persistence round-trips faithfully (M5, port of the
 * v1 spec onto the v2 workspace bar + WS v5 documents).
 *
 * - a saved workspace comes back as the same workspace after OTHER
 *   workspaces were loaded in between (digest compared to ITSELF);
 * - the auto-save restores the bench across a reload, including collapsed
 *   panels;
 * - a REAL legacy v4 blob (captured from the v1 template code, not
 *   hand-written) appears under Legacy in the Load menu and imports:
 *   generator → source, sweeps → programs, graphs → tiles;
 * - Space is the global transport (run/stop), guarded while typing.
 */
import { readFileSync } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test } from "./adapter/fixtures";

const V4_BLOB = readFileSync(
  path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    "fixtures",
    "workspace-v4.json"
  ),
  "utf8"
);

test("save → load round-trips sources, layout and programs", async ({ app }) => {
  // A bench touching every slice: a parametrised re-routed source, a
  // different grid, an extra program.
  const id = await app.addSine();
  await app.setSineFrequency(id, 3000);
  await app.setSineRoute(id, "right");
  await app.setLayoutPattern("1x2");
  await app.addProgram("thd");

  // Name it first so the digest (which includes the name) is stable.
  await app.saveWorkspaceAs("e2e round-trip");
  const before = await app.workspaceDigest();

  // Wander off: a template load replaces everything.
  await app.loadWorkspace("Quick THD Check", "template");
  expect(await app.workspaceDigest()).not.toEqual(before);

  // Come home: the digest must be IDENTICAL to what was saved.
  await app.loadWorkspace("e2e round-trip", "saved");
  expect(await app.workspaceDigest()).toEqual(before);
});

test("auto-save restores the bench (and collapsed panels) across a reload", async ({
  app,
}) => {
  const id = await app.addSine();
  await app.setSineFrequency(id, 3000);
  await app.toggleCollapse("programs");
  expect(await app.panelCollapsed("programs")).toBe(true);
  await app.saveWorkspaceAs("Reload bench");
  const before = await app.workspaceDigest();

  // The debounced auto-save must land before the reload throws the page away.
  await app.waitForAutoSave("Reload bench");
  await app.boot();

  expect(await app.workspaceDigest()).toEqual(before);
  expect(await app.panelCollapsed("programs")).toBe(true);
});

test("a legacy v4 save imports: source, programs and tiles land in their panels", async ({
  app,
}) => {
  // The blob is exactly what the v1 frontend wrote for this workspace
  // (generated by src/dashboard/store.ts — the "capture real v4 blobs"
  // risk item), seeded behind the bar's back.
  await app.putLocalStorage("qa40x-dash-ws:Amp / DAC bench", V4_BLOB);

  const menu = await app.workspaceMenu();
  expect(menu.templates).toContain("First Look");
  expect(menu.legacy).toContain("Amp / DAC bench");

  await app.loadWorkspace("Amp / DAC bench", "legacy");

  const digest = (await app.workspaceDigest()) as {
    workspace: { name: string };
    layout: {
      pattern: string;
      order: string[];
      tiles: Record<string, { kind: string; traces: string[]; showPhase: boolean }>;
    };
    sources: {
      order: string[];
      byId: Record<
        string,
        { kind: string; route: string; frequencyHz?: number; levelDbv?: number }
      >;
    };
    programs: { order: string[]; byId: Record<string, { kind: string }> };
    traces: { id: string; label: string }[];
  };

  // The generator became a ready sine source with its params and route.
  expect(digest.workspace.name).toBe("Amp / DAC bench");
  expect(digest.sources.byId["t-gen"]).toMatchObject({
    kind: "sine",
    route: "both",
    frequencyHz: 1000,
    levelDbv: -12,
  });

  // Both sweeps are programs with result traces in the pool.
  expect(digest.programs.order).toEqual(["t-thd", "t-fr"]);
  const poolLabels = digest.traces.map((t) => t.label);
  expect(poolLabels).toContain("THD vs freq");
  expect(poolLabels).toContain("FR L");

  // Graphs landed as tiles: 2×2, spectrum / sweep / sweep(∠) / scope.
  expect(digest.layout.pattern).toBe("2x2");
  expect(digest.layout.order).toEqual(["g-spec", "g-thd", "g-fr", "g-scope"]);
  expect(digest.layout.tiles["g-spec"].kind).toBe("spectrum");
  expect(digest.layout.tiles["g-thd"].traces).toEqual(["t-thd"]);
  expect(digest.layout.tiles["g-fr"].showPhase).toBe(true);
  expect(digest.layout.tiles["g-scope"].kind).toBe("scope");

  // And the panels agree (the user-visible check, not just the store):
  // program traces live in the Programs panel, hardware endpoints in Traces.
  const progNames = await app.drv.eval(
    () =>
      Array.from(
        document.querySelectorAll('[data-testid="programs-list"] .programs__name')
      ).map((n) => n.textContent ?? ""),
    undefined as void
  );
  expect(progNames).toContain("THD vs freq");
  expect(progNames).toContain("FR L");
  expect((await app.poolRows()).map((r) => r.label)).toContain("Input L");
});

test("Space runs and stops the stream; typing is never hijacked", async ({
  app,
}) => {
  await app.waitConnected();

  await app.pressSpace();
  await expect.poll(() => app.streaming()).toBe(true);

  await app.pressSpace();
  await expect.poll(() => app.streaming()).toBe(false);

  // With a field focused, Space types a space instead of a transport.
  await app.drv.eval(() => {
    const input = document.querySelector<HTMLInputElement>('[data-testid="ws-name"]')!;
    input.focus();
    input.dispatchEvent(
      new KeyboardEvent("keydown", { code: "Space", bubbles: true, cancelable: true })
    );
  }, undefined as void);
  expect(await app.streaming()).toBe(false);
});
